FROM openresty/openresty:1.13.6.2-2-centos

# Runtime dependencies
RUN yum -y install \
  bash \
  coreutils \
  curl \
  diffutils \
  grep \
  openssl \
  sed

# Build dependencies.
RUN yum -y install make

# Test dependencies
RUN yum -y install epel-release && \
  yum -y install \
    gcc \
    git \
    lsof \
    lua \
    procps-ng \
    redis \
    sudo \
    https://bin.equinox.io/a/6iuHhJeWypm/ngrok-2.3.34-linux-amd64.rpm

RUN mkdir /app
WORKDIR /app

COPY Makefile /app/Makefile
RUN make install-test-deps

ENV PATH="/tmp/resty-auto-ssl-test-luarocks/bin:${PATH}"
ENV LUA_PATH="/tmp/resty-auto-ssl-test-luarocks/share/lua/5.1/?.lua;/tmp/resty-auto-ssl-test-luarocks/share/lua/5.1/?/init.lua;${LUA_PATH}"
ENV LUA_CPATH="/tmp/resty-auto-ssl-test-luarocks/lib/lua/5.1/?.so;${LUA_CPATH}"

COPY . /app

CMD ["bash"]
