FROM openresty/openresty:1.21.4.1-0-centos

# Runtime dependencies
RUN yum -y install \
  bash \
  curl \
  diffutils \
  grep \
  openssl \
  sed

# Build dependencies.
RUN yum -y install make

# Test dependencies
RUN yum -y install epel-release && \
  yum -y install \
    gcc \
    git \
    lsof \
    lua \
    procps-ng \
    redis \
    sudo
RUN curl -fsSL -o /tmp/ngrok.tar.gz https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz && \
  tar -xvf /tmp/ngrok.tar.gz -C /usr/local/bin/ && \
  rm -f /tmp/ngrok.tar.gz

RUN mkdir /app
WORKDIR /app

COPY Makefile /app/Makefile
RUN make install-test-deps

ENV PATH="/tmp/resty-auto-ssl-test-luarocks/bin:${PATH}"
ENV LUA_PATH="/tmp/resty-auto-ssl-test-luarocks/share/lua/5.1/?.lua;/tmp/resty-auto-ssl-test-luarocks/share/lua/5.1/?/init.lua;${LUA_PATH}"
ENV LUA_CPATH="/tmp/resty-auto-ssl-test-luarocks/lib/lua/5.1/?.so;${LUA_CPATH}"

COPY . /app

CMD ["bash"]
