FROM openresty/openresty:1.15.8.2-1-bionic

ENV DEBIAN_FRONTEND noninteractive

# Runtime dependencies
RUN apt-get update && \
  apt-get -y install \
    bash \
    coreutils \
    curl \
    diffutils \
    grep \
    openssl \
    sed

# Build dependencies.
RUN apt-get update && \
  apt-get -y install make

# Test dependencies
RUN apt-get update && \
  apt-get -y install \
    git \
    lsof \
    lua5.2 \
    redis-server \
    sudo \
    tzdata && \
  curl -fsSL -o /tmp/ngrok.deb https://bin.equinox.io/a/b2wQezFbsHk/ngrok-2.3.34-linux-amd64.deb && \
  dpkg -i /tmp/ngrok.deb || apt-get -fy install && \
  rm -f /tmp/ngrok.deb

RUN mkdir /app
WORKDIR /app

COPY Makefile /app/Makefile
RUN make install-test-deps

ENV PATH="/tmp/resty-auto-ssl-test-luarocks/bin:${PATH}"
ENV LUA_PATH="/tmp/resty-auto-ssl-test-luarocks/share/lua/5.1/?.lua;/tmp/resty-auto-ssl-test-luarocks/share/lua/5.1/?/init.lua;${LUA_PATH}"
ENV LUA_CPATH="/tmp/resty-auto-ssl-test-luarocks/lib/lua/5.1/?.so;${LUA_CPATH}"

COPY . /app

CMD ["bash"]
