FROM openresty/openresty:1.13.6.2-2-alpine-fat

RUN mkdir /app
WORKDIR /app

# Runtime dependencies
RUN apk add --no-cache \
    bash \
    coreutils \
    curl \
    diffutils \
    grep \
    openssl \
    sed

# Build dependencies.
RUN apk add --no-cache \
  make

# Test dependencies
RUN apk add --no-cache \
    findutils \
    gcc \
    git \
    lsof \
    lua \
    procps \
    redis \
    sudo \
    wget && \
  curl -fsSL -o /tmp/ngrok.tar.gz https://bin.equinox.io/a/4dXSqUzbJK6/ngrok-2.3.34-linux-amd64.tar.gz && \
  tar -xvf /tmp/ngrok.tar.gz -C /usr/local/bin/ && \
  rm -f /tmp/ngrok.tar.gz && \
  chmod +x /usr/local/bin/ngrok

COPY Makefile /app/Makefile
RUN make install-test-deps

ENV PATH="/app/spec/tmp/test-luarocks/bin:${PATH}"
ENV LUA_PATH="/app/spec/tmp/test-luarocks/share/lua/5.1/?.lua;/app/spec/tmp/test-luarocks/share/lua/5.1/?/init.lua;${LUA_PATH}"
ENV LUA_CPATH="/app/spec/tmp/test-luarocks/lib/lua/5.1/?.so;${LUA_CPATH}"

COPY . /app
