FROM openresty/openresty:1.21.4.1-0-jammy

ENV DEBIAN_FRONTEND noninteractive

# Runtime dependencies
RUN apt-get update && \
  apt-get -y install \
    bash \
    curl \
    diffutils \
    grep \
    openssl \
    sed

# Build dependencies.
RUN apt-get update && \
  apt-get -y install make

# Test dependencies
RUN apt-get update && \
  apt-get -y install \
    git \
    lsof \
    lua5.4 \
    redis-server \
    sudo \
    tzdata
RUN curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | \
    sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && \
    echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | \
    sudo tee /etc/apt/sources.list.d/ngrok.list && \
    sudo apt update && \
    sudo apt install ngrok

RUN mkdir /app
WORKDIR /app

COPY Makefile /app/Makefile
RUN make install-test-deps

ENV PATH="/tmp/resty-auto-ssl-test-luarocks/bin:${PATH}"
ENV LUA_PATH="/tmp/resty-auto-ssl-test-luarocks/share/lua/5.1/?.lua;/tmp/resty-auto-ssl-test-luarocks/share/lua/5.1/?/init.lua;${LUA_PATH}"
ENV LUA_CPATH="/tmp/resty-auto-ssl-test-luarocks/lib/lua/5.1/?.so;${LUA_CPATH}"

COPY . /app

CMD ["bash"]
