local lock = require "resty.lock"
local resty_random = require "resty.random"
local start_sockproc = require "resty.auto-ssl.utils.start_sockproc"
local str = require "resty.string"

-- Generate a secret token used for the letsencrypt.sh bash hook script to
-- communicate with the internal HTTP API hook server.
--
-- The internal HTTP API should only be listening on a private port on
-- 127.0.0.1, so it should only be accessible internally already, but this
-- secret token is an extra precaution to ensure the server is not accidentally
-- opened up or proxied to the outside world.
local function generate_hook_sever_secret()
  -- Skip if secret is already generated by another worker.
  if ngx.shared.auto_ssl:get("hook_server:secret") then
    return
  end

  -- Generate the secret token.
  local random = resty_random.bytes(32)
  ngx.shared.auto_ssl:set("hook_server:secret", str.to_hex(random))
end

local function generate_config(auto_ssl_instance)
  local base_dir = auto_ssl_instance:get("dir")

  os.execute("mkdir -p " .. base_dir .. "/letsencrypt/conf.d")
  os.execute("mkdir -p " .. base_dir .. "/letsencrypt/.acme-challenges")

  local file, err = io.open(base_dir .. "/letsencrypt/config.sh", "w")
  if err then
    ngx.log(ngx.ERR, "auto-ssl: failed to open letsencrypt config file")
  else
    file:write('# This file will be overwritten by resty-auto-ssl.\n')
    file:write('# Place any customizations in ' .. base_dir .. '/letsencrypt/conf.d\n\n')
    file:write('CONFIG_D="' .. base_dir .. '/letsencrypt/conf.d"\n')

    local ca = auto_ssl_instance:get("ca")
    if ca then
      file:write('CA="' .. ca .. '"\n')
    end

    file:close()
  end
end

local function setup_storage(auto_ssl_instance)
  local adapter = require(auto_ssl_instance:get("storage_adapter"))
  local adapter_instance = adapter.new(auto_ssl_instance)
  adapter_instance:setup()

  local storage = require "resty.auto-ssl.storage"
  local storage_instance = storage.new(adapter_instance)
  auto_ssl_instance:set("storage", storage_instance)
end

local function setup(auto_ssl_instance)
  -- Use a lock to ensure setup tasks don't overlap (even if multiple workers
  -- are starting).
  local generate_lock, new_lock_err = lock:new("auto_ssl", { ["timeout"] = 0 })
  if new_lock_err then
    ngx.log(ngx.ERR, "auto-ssl: failed to create lock: ", new_lock_err)
    return
  end

  local _, lock_err = generate_lock:lock("init_worker_setup")
  if lock_err then
    return
  end

  generate_hook_sever_secret()
  generate_config(auto_ssl_instance)
  setup_storage(auto_ssl_instance)

  local ok, unlock_err = generate_lock:unlock()
  if not ok then
    ngx.log(ngx.ERR, "auto-ssl: failed to unlock: ", unlock_err)
  end
end

return function(auto_ssl_instance)
  start_sockproc()
  setup(auto_ssl_instance)
end
